# 1) Base image
FROM python:3.12.7-slim AS runtime

# 2) Environment
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# 3) OS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    netcat-openbsd \
  && rm -rf /var/lib/apt/lists/*


# 4) Create non-root user
RUN useradd -m appuser

# 5) Workdir
WORKDIR /app

# 6) Dependencies (cached when requirements.txt unchanged)
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# 7) App source
COPY . /app

# 8) Entrypoint: copy, chmod, and set ownership
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh \
    && chown appuser:appuser /entrypoint.sh \
    && chown -R appuser:appuser /app

# 9) Drop privileges
USER appuser

# 10) Networking
EXPOSE 8000

# 11) Start-up
ENTRYPOINT ["/entrypoint.sh"]
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]

