# Generated by Django 5.2.5 on 2026-04-03 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        db_index=True,
                        help_text="Asterisk UniqueID for the channel",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=200)),
                ("caller_id", models.CharField(blank=True, max_length=100)),
                ("campaign_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                (
                    "stt_engine",
                    models.CharField(
                        default="vosk",
                        help_text="STT engine used  (vosk | whisper | google)",
                        max_length=50,
                    ),
                ),
                (
                    "tts_engine",
                    models.CharField(
                        default="melotts",
                        help_text="TTS engine used  (melotts | gtts | elevenlabs)",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="BCP-47 language code, e.g. en / ur / ar",
                        max_length=10,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        help_text="Final outcome: SALE, NI, DNC, TRANSFER …",
                        max_length=100,
                    ),
                ),
                ("transferred_to", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "turn_type",
                    models.CharField(
                        choices=[
                            ("stt", "Caller spoke  → STT text"),
                            ("tts", "Bot replied   → TTS audio"),
                            ("err", "Engine error"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Raw STT output or TTS input text"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, help_text="STT confidence score 0-1", null=True
                    ),
                ),
                (
                    "audio_file",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to the saved audio file",
                        max_length=300,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Engine processing time in ms"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="voice.voicesession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
